#!/usr/bin/env ruby
# in: media-old.xml media-new.xml
# out: evenements.json
require 'rexml/document'
require 'json'

old_file = File.new(ARGV[0])
new_file = File.new(ARGV[1])
old_doc = REXML::Document.new(old_file.read)
new_doc = REXML::Document.new(new_file.read)
json = {}
json[:date_heure_generation] = new_doc.root.attributes['date_heure_generation']
json[:date_heure_generation_previous] = old_doc.root.attributes['date_heure_generation']

def fmt(elem, type)
  case type
  when :i
    elem.text.to_i
  when :f
    elem.text.to_f
  when :s
    elem.text
  else
  elem
  end
end

candidats_avant = {}
candidats_maintenant = {}
json[:postes] = []
#json[:mairie_avant] = mairie_avant
#json[:mairie_maintenant] = mairie_maintenant

old_doc.root.each_element('/resultats/resultats_maire/sommaire/candidat | /resultats/resultats_postes/poste/candidat') do |tag|
  candidats_avant[tag.attributes['id'].to_i] = {
    'nb_voix_obtenues' => tag.elements['nb_voix_obtenues'].text.to_i,
    'nb_voix_majorite' => tag.elements['nb_voix_majorite'].text.to_i,
  }
end
new_doc.root.each_element('/resultats/resultats_maire/sommaire/candidat | /resultats/resultats_postes/poste/candidat') do |tag|
  id = tag.attributes['id'].to_i
  candidat = {
    'nom' => :s,
    'prenom' => :s,
    'nb_voix_obtenues' => :i,
    'nb_voix_majorite' => :i
  }.inject({}) { |h, (k, v)| h[k] = fmt(tag.elements[k], v); h }
  candidat[:id] = id
  candidat[:parti] = tag.elements['parti'].attributes['id'].to_i
  candidats_maintenant[id] = candidat

  before = candidats_avant[id]['nb_voix_majorite']
  after = candidat['nb_voix_majorite']
  candidat['nb_voix_majorite'] = [before, after]
  candidat['nb_voix_obtenues'] = [candidats_avant[id]['nb_voix_obtenues'], candidat['nb_voix_obtenues']]
  if before > 0 && after == 0
    candidat[:evenement] = :perdant
    json[:postes] << candidat
  elsif before == 0 && after > 0
    candidat[:evenement] = :gagnant
    json[:postes] << candidat
  end
end


# Conseil de ville
def sieges_par_parti(doc, types)
  sieges = Hash.new
  types_expr = types.map{|t| "type = '#{t}'"}.join(' or ')
  doc.root.each_element("/resultats/resultats_postes/poste[#{types_expr}]/candidat[nb_voix_majorite != '']") do |tag|
    candidat = {
      :id => tag.attributes["id"].to_i,
      :parti => parti = tag.elements["parti"].attributes["id"].to_i,
      :nom => tag.elements["nom"].text,
      :prenom => tag.elements["prenom"].text,
      :poste_id => poste_id = tag.elements['../@id'],
      :poste => tag.elements['../nom'].text
    }
    s = sieges[parti]
    sieges[parti] = s = {} unless s
    s[poste_id] = candidat
    #puts "#{parti}: #{poste_id} -> #{candidat}"
  end
  sieges
end

sieges_avant = sieges_par_parti(old_doc, ['CV', 'MC'])
sieges_apres = sieges_par_parti(new_doc, ['CV', 'MC'])
nb_par_parti = [sieges_avant, sieges_apres].map {|s|
  s.inject({}) { |h, (parti, sieges)| h[parti] = sieges.count; h }
}
majorite = nb_par_parti.map {|sieges|
  maj = [0,0]
  sieges.each {|parti, sieges|
    maj = [parti, sieges] if sieges > maj[1] 
  }
  maj[0]
}
json[:conseil_ville] = {}
json[:conseil_ville][:partis] = nb_par_parti
if majorite[0] != majorite[1]
  json[:conseil_ville][:majoritaire] = majorite[1]
  #json[:conseil_ville][:avant] = sieges_avant
  #json[:conseil_ville][:apres] = sieges_apres
end

puts JSON.pretty_generate(json)