#!/usr/bin/env ruby

dir_in = "media"
dir_out = "public"

system "mkdir -p #{dir_in} #{dir_out}"

while true
  start = Time.now
  file = "#{dir_in}/#{start.strftime('%Y%m%d-%H%M')}"
  json = "#{file}.json"

  system "./download #{file}.xml"

  puts "Converting to JSON..."
  system "./xml_to_json #{file}.xml > #{file}.json"

  puts "Extracting events..."
  system "./diff_media #{dir_in}/previous.xml #{file}.xml > #{file}_events.json"

  # Publish (not-so)-atomically
  system "cp -v #{file}.xml #{dir_in}/previous.xml"
  system "cp -v #{file}.xml #{dir_out}/media.xml"
  system "cp -v #{file}.json #{dir_out}/media.json"
  system "cp -v #{file}_events.json #{dir_out}/events.json"
  
  elapsed = Time.now.to_i - start.to_i
  puts "Imported in #{elapsed} seconds."
  sleep_time = [0, 120 - elapsed].max
  puts "Sleeping for #{sleep_time} seconds."
  sleep(sleep_time)
end

